### ISSUE TITLE
Backbone 1.2.0 with BackboneRelational not working?

### ISSUE THREAD

**Issue by benmcmaster** [PaulUithol/Backbone-relational#531] opened 2015-06-04 15:45 UTC
I just upgraded to the recent release of Backbone.js (1.2.0). Now my relational models are not mapping correctly.

```
class Vimify.Models.DayStructure extends Backbone.RelationalModel

	relations: [
		{
			type: Backbone.HasMany
			key: 'groups'
			relatedModel: 'Vimify.Models.Group'
			collectionType: 'Vimify.Collections.Groups'
		}
	]
```
It looks like the relations are not resolving. "groups" remains an array, and not a collection of models. 

Is anyone else having troubles with upgrading to Backbone 1.2.0?

**Comment by PaulUithol** [comment] 2015-06-04 19:04
I did take a look at Backbone 1.2 recently; there are a couple of failing tests, but it seemed to be limited to some `change` event behavior (which is already quite tricky, and sometimes debatable) and the Collection.remove event being renamed `update` or something like that.

Would be helpful here as well to have a running example.

**Comment by philfreo** [comment] 2015-06-09 20:18
Backbone 1.2.0 itself had some bugs/regressions, but Backbone 1.2.1 is out now and Relational's tests are still failing with it.

**Comment by PaulUithol** [comment] 2015-06-12 09:24
Yeah, I know; am looking into that. But it's a couple of small things (of course, some `change` events..); no big things like this.

**Comment by littlell** [comment] 2015-07-10 08:31
Is this problem fixed? Thanks.

**Comment by philfreo** [comment] 2015-08-10 23:05
Any word?

**Comment by PaulUithol** [comment] 2015-08-19 08:53
Yes, there are a couple of tests failing with Backbone 1.2; but nothing major that I can see (am looking at them though). Don't see any relations failing in our app either. Could you try to make a jsfiddle or similar out of your case?

**Comment by PaulUithol** [comment] 2015-08-19 10:06
Sorry, I'm quite out of it it seems (still in Tanzania). Took me a looongg and winding debugging session just to figure out that the root cause for almost all issues with 1.2 is the same; the addition of `Collection._removeModels`. Will be fixed very soon.

**Comment by philfreo** [comment] 2015-08-21 17:49
@PaulUithol Thanks for the update! Backbone 1.2.1 is now out also :) 

http://backbonejs.org/#changelog

**Comment by philfreo** [comment] 2015-08-21 17:49
@PaulUithol Thanks for the update! Backbone 1.2.2 is now out also :)

http://backbonejs.org/#changelog

**Comment by PaulUithol** [comment] 2015-08-21 18:05
Thanks, upgrading the test lib to that! Looks pretty innocent.

**Comment by PaulUithol** [comment] 2015-08-21 18:06
Or maybe not.. don't know if this is intentional, but collection.set(null) used to empty the collection; doesn't anymore (plain Backbone).

```
a = new Backbone.Collection()
Object { length=0,  models=[0],  _byId={...},  more...}
a.add({})
Object { cid="c15",  attributes={...},  collection={...},  more...}
a.set(null)
undefined
a
Object { length=1,  models=[1],  _byId={...},  more...}
```

**Comment by MiguelSR** [comment] 2015-08-27 09:48
Hello.

Is the current master version (0.10.0) compatible with Backbone 1.2 yet?

I've seen that there one test with the previously discussed _removeModels but not sure if it's already working.

Thank you,
Miguel.

**Comment by PaulUithol** [comment] 2015-08-27 10:23
Yes, it should work fine. See 0731ff391e3159dfac617e5834b33adef9500b49. Closing this one, since the title is misleading, and the author's not responding.

**Closed by PaulUithol** 2015-08-27 10:23 UTC
