### ISSUE TITLE
 Question: Working with mysql data representing models as table rows

### ISSUE THREAD

**Issue by alvassin** [PaulUithol/Backbone-relational#390] opened 2013-07-29 13:29 UTC
Imagine we have two tables in mysql: cars and engines.

Cars table row will have following structue:

 - `id`: int
 - `engineId`: int (foreign key to `engines.id` column)
 - `brand`: string

Engines table row this one:

 - `id`: int,
 - `type`: string (imagine we have electric and diesel engines)

So, i want to retrieve all data from these tables, create model collections on client side and finally display table with merged results:

 - car id
 - brand name
 - engine type

So, i've tried many examples, but i can't get what i am doing wrong. Can you assist please?

    // Create car model
    window.Car = Backbone.RelationalModel.extend({

    });

    // Create engine model
    window.Engine = Backbone.RelationalModel.extend({
      relations: [{
        type: 'HasMany',
        key: 'cars',
        relatedModel: 'Car',
        reverseRelation: {
          key: 'engine',
          includeInJSON : 'engineId',
        }
      }]
    });
    
    // Create engine instance
    var engine = new window.Engine({
      id : 1,
      type : 'electric',
    });
    
    // Create car instance
    var car = new window.Car({
      id       : 1,
      brand    : 'Toyota',
      engineId : 1, 
    });
    
    // i expect to get 'electric'
    console.log(car.getRelation('engine').type);

**Comment by feeekkk** [comment] 2016-06-07 18:38
I think the problem is just that you should be using `car.get('engine').get('type');` `car.getRelation('engine')` returns the _Backbone.Relation instance_, rather than the attributes field that it seems you are trying to access. Instead, just retrieve the _related model instance_ and use the typical backbone get to retrieve the field.

**Comment by bpatram** [comment] 2016-06-28 14:16
That seems to be the issue most likely. I am closing this issue; if it's found that that is not the correct fix I will re-open it.

**Closed by bpatram** 2016-06-28 14:16 UTC
Labels: question
